# Generated by Django 5.1.3 on 2025-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_price_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_limit',
            field=models.IntegerField(blank=True, help_text='Miesięczny limit dla beneficjenta', null=True),
        ),
    ]
