# Generated by Django 5.1.3 on 2025-03-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_supplyorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockentry',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
