# Generated by Django 5.1.3 on 2025-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockentry_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreduction',
            name='stock_type',
            field=models.CharField(choices=[('physical', 'Fizyczny'), ('virtual', 'Wirtualny')], default='physical', max_length=10),
        ),
    ]
