# Generated by Django 5.1.3 on 2025-03-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_status'),
        ('stock', '0004_stockreduction_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreduction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_reductions', to='products.orderitem'),
        ),
    ]
