# Generated by Django 5.1.3 on 2025-01-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_cart_cartitem_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('payment_type', models.CharField(choices=[('contribution', 'Wpłata od wspierającego'), ('order_payment', 'Płatność za zamówienie'), ('refund', 'Zwrot środków'), ('expense', 'Wydatek'), ('other', 'Inne')], max_length=20, verbose_name='Typ płatności')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.order', verbose_name='Powiązane zamówienie')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_payments', to=settings.AUTH_USER_MODEL, verbose_name='Powiązany użytkownik')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
                'ordering': ['-created_at'],
            },
        ),
    ]
