# Generated by Django 5.1.3 on 2025-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sender',
            field=models.TextField(blank=True, null=True, verbose_name='Nadawca'),
        ),
    ]
