# Generated by Django 5.1.3 on 2025-03-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='stock.supplier'),
        ),
    ]
