# Generated by Django 5.1.3 on 2025-03-25 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_payment_related_order_items'),
        ('products', '0009_orderitem_buyer'),
        ('users', '0004_profile_monthly_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyContributionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('limit', models.IntegerField()),
                ('order_items', models.ManyToManyField(blank=True, related_name='monthly_usage', to='products.orderitem')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usage', to='users.profile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('profile', 'year', 'month')},
            },
        ),
    ]
