# Generated by Django 5.1.3 on 2025-06-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_monthlycontributionusage'),
        ('products', '0010_cartitem_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota alokacji')),
                ('allocation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data alokacji')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='products.orderitem', verbose_name='Element zamówienia')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment', verbose_name='Płatność')),
            ],
            options={
                'verbose_name': 'Alokacja płatności',
                'verbose_name_plural': 'Alokacje płatności',
                'ordering': ['-allocation_date'],
            },
        ),
    ]
