from django.urls import path
from stock.views import (
    api_delete_stock_reduction,
    api_list_stock_reductions,
    api_update_stock_reduction,
)
from stock.suppliers_api import (
    api_add_supplier,
    api_delete_supplier,
    api_edit_supplier,
    api_list_suppliers,
)
from stock.supply_orders_api import (
    api_assign_supply_order_invoice,
    api_create_supply_order,
    api_delete_supply_order,
    api_list_supply_orders,
    api_update_supply_order,
)
from . import views
from . import carts_views
from . import cart_create_order

urlpatterns = [
    path('', views.home, name='home'),
    path('api/products/', views.api_products_list, name='api_products_list'),
    path('api/admin/price-lists/', views.api_admin_price_lists, name='api_admin_price_lists'),
    path('api/admin/price-lists/add/', views.api_add_price_list, name='api_add_price_list'),
    path(
        'api/admin/price-lists/delete/<int:price_list_id>/',
        views.api_delete_price_list,
        name='api_delete_price_list',
    ),
    path('api/admin/price-lists/save/', views.api_save_price, name='api_save_price'),
    path('api/admin/products/', views.api_admin_products, name='api_admin_products'),
    path('api/admin/products/add/', views.api_admin_add_product, name='api_admin_add_product'),
    path('api/admin/shipments/add/', views.api_admin_add_shipment, name='api_admin_add_shipment'),
    path('api/admin/products/edit/<int:product_id>/', views.api_admin_edit_product, name='api_admin_edit_product'),
    path('api/admin/shipments/edit/<int:product_id>/', views.api_admin_edit_shipment, name='api_admin_edit_shipment'),
    path('api/admin/products/delete/<int:product_id>/', views.api_admin_delete_product, name='api_admin_delete_product'),
    path('api/admin/product-categories/add/', views.api_admin_add_product_category, name='api_admin_add_product_category'),
    path(
        'api/admin/product-categories/delete/<int:category_id>/',
        views.api_admin_delete_product_category,
        name='api_admin_delete_product_category',
    ),
    path(
        'api/admin/product-categories/edit/<int:category_id>/',
        views.api_admin_edit_product_category,
        name='api_admin_edit_product_category',
    ),
    path(
        'api/admin/product-categories/icons/',
        views.api_admin_product_category_icons,
        name='api_admin_product_category_icons',
    ),
    path('api/buyers/', views.api_buyers_list, name='api_buyers_list'),
    path('api/cart/change-buyer/', views.api_cart_change_buyer, name='api_cart_change_buyer'),
    path('api/cart/items/', views.api_cart_items, name='api_get_cart_items'),
    path('api/cart/items/decrease/', views.api_decrease_cart_item_quantity, name='api_decrease_cart_item_quantity'),
    path('api/cart/items/increase/', views.api_increase_cart_item_quantity, name='api_increase_cart_item_quantity'),
    path('products/', views.products, name='products'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('prices/', views.prices, name='prices'),
    path('prices/add/', views.add_price_list, name='add_price_list'),
    path('prices/save/', views.save_price, name='save_price'),
    path('change-buyer/', views.change_buyer, name='change_buyer'),
    path('cart/update/', carts_views.update_cart, name='update_cart'),
    path('cart/get-items/', carts_views.get_cart_items, name='get_cart_items'),
    path('cart/remove/', carts_views.remove_cart_item, name='remove_cart_item'),
    path('cart/order/', cart_create_order.create_order, name='create_order'),
    path('api/cart/order/', views.api_create_order, name='api_create_order'),
    path('api/orders/', views.api_list_of_orders_for_buyer, name='api_list_of_orders_for_buyer'),
    path('api/orders/admin/', views.api_list_of_orders_for_admin, name='api_list_of_orders_for_admin'),
    path('api/orders/<int:order_id>/status/', views.api_update_order_status, name='api_update_order_status'),
    path('api/orders/<int:order_id>/payment-status/', views.api_update_order_payment_status, name='api_update_order_payment_status'),
    path('api/orders/delete/<int:order_id>/', views.api_delete_order, name='api_delete_order'),
    path('api/stock/reductions/', api_list_stock_reductions, name='api_list_stock_reductions'),
    path(
        'api/stock/reductions/delete/<int:reduction_id>/',
        api_delete_stock_reduction,
        name='api_delete_stock_reduction',
    ),
    path(
        'api/stock/reductions/update/<int:reduction_id>/',
        api_update_stock_reduction,
        name='api_update_stock_reduction',
    ),
    path('api/supply-orders/', api_list_supply_orders, name='api_list_supply_orders'),
    path('api/supply-orders/create/', api_create_supply_order, name='api_create_supply_order'),
    path(
        'api/supply-orders/update/<int:supply_order_id>/',
        api_update_supply_order,
        name='api_update_supply_order',
    ),
    path(
        'api/supply-orders/delete/<int:supply_order_id>/',
        api_delete_supply_order,
        name='api_delete_supply_order',
    ),
    path(
        'api/supply-orders/assign-invoice/',
        api_assign_supply_order_invoice,
        name='api_assign_supply_order_invoice',
    ),
    path('api/admin/suppliers/', api_list_suppliers, name='api_list_suppliers'),
    path('api/admin/suppliers/add/', api_add_supplier, name='api_add_supplier'),
    path('api/admin/suppliers/edit/<int:supplier_id>/', api_edit_supplier, name='api_edit_supplier'),
    path(
        'api/admin/suppliers/delete/<int:supplier_id>/',
        api_delete_supplier,
        name='api_delete_supplier',
    ),
    path('orders/', views.orders, name='orders'),
    path('orders/update-status/', views.update_order_status, name='update_order_status'),
    path('orders/delete/<int:order_id>/', views.delete_order, name='delete_order'),
    path('orders/assign-buyer/', views.assign_buyer_to_order_item, name='assign_buyer_to_order_item'),
    path('products/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('products/add-category/', views.add_category, name='add_category'),
    path('cart/toggle/', carts_views.toggle_cart, name='toggle_cart'),
    path('cart/determine-contribution-usage/', carts_views.determine_contribution_usage, name='determine_contribution_usage'),
]
