# Generated by Django 5.1.3 on 2024-12-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_pricelist_price_remove_pricelist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
