# Generated by Django 5.1.3 on 2025-02-26 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_cartitem_order_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria produktu',
                'verbose_name_plural': 'Kategorie produktów',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=23.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_unit',
            field=models.CharField(choices=[('l', 'Litry'), ('kg', 'Kilogramy'), ('pcs', 'Sztuki')], default='pcs', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='volume_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Przyjęte'), ('shipped', 'Nadane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.productcategory'),
        ),
    ]
