# Generated by Django 5.1.3 on 2025-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekujące'), ('accepted', 'Przyjęte'), ('shipped', 'Nadane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='pending', max_length=20),
        ),
    ]
