# Generated by Django 5.1.3 on 2026-04-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_cartitem_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='subtotal',
        ),
    ]
